### ISSUE TITLE
[Info APi] Refactor modules and double-check all endpoints

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/tara-erc20-info-api#14]
1. New DPOS module that will be used both the nodes and the staking module.
2. Double check all endpoints and do the calculations manually. There might be something wrong there. Ex: https://github.com/Taraxa-project/tara-erc20-info-api/blob/main/src/node/node.service.ts#L84

**Comment by VargaElod23** [comment]
In the meantime I remembered why do we need 100 there: the validators come in batches of up to 100 :)

**Comment by rattrap** [comment]
Yeah but that param is the "page", not "skip" field

**Comment by VargaElod23** [comment]
- [x] Decommission `cumulativeCommission` endpoint until subgraph is done.
- [x] implements `cumulativeRewards` endpoint.
- [x] Fix contributions endpoint.
- [x] Correct avgStakingYield calculation.
- [x] Switch to 1 min cache for prices, use cacheManager.
- [x] Unify returns as strings.
- [x] Avoid floating point rounding after the 52nd bit.
